//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_CalculoAnual
    {
        public int id { get; set; }
        public int idEmpleado { get; set; }
        public int idEmpresa { get; set; }
        public int idEjercicio { get; set; }
        public int idPeriodo { get; set; }
        public int idNomina { get; set; }
        public decimal baseGravable { get; set; }
        public decimal Exento { get; set; }
        public decimal subCausado { get; set; }
        public decimal isrAntes { get; set; }
        public decimal isrPagado { get; set; }
        public decimal isrRetener { get; set; }
        public decimal saldoFavor { get; set; }
        public bool status { get; set; }
    }
}
